---
- name: Load OS specific variables
  include_vars: ../vars/debian.yml

- name: Update server
  apt:
    upgrade: full
    update_cache: yes
  register: update

- name: Install Guacamole library requirements
  apt:
    name:
      - libcairo2-dev
      - libjpeg62-dev
      - libpng-dev
      - libossp-uuid-dev
      - libfreerdp-dev
      - libpango1.0-dev
      - libssh2-1-dev
      - libssh-dev
      - tomcat9
      - tomcat9-admin
      - tomcat9-user
      - haveged # fixes /dev/random issue
      # to compile the intial code
      - autotools-dev
      - autoconf
      - automake
      - gcc
      - make
      # for SQL Auth
      - mysql-server
      - mysql-client
      - mysql-common
      - mysql-utilities
      - python-pymysql
      - python3-pymysql
    state: present
    install_recommends: no

- name: "Start MySQL"
  service:
    name: mysql
    state: started
    enabled: yes

- name: Get Debian MySQL System Account file
  slurp:
    src: /etc/mysql/debian.cnf
  register: mysql_creds

- name: Load Debian MySQL System Facts
  set_fact:
    harden_db: false
    db_admin_user: |-
      {% set ns=namespace() %}
      {%- for myline in (mysql_creds['content'] | b64decode).splitlines() -%}
        {%- if 'user' in myline -%}
          {%- set ns.mydata=myline | regex_replace('^user\s*=\s*','') | regex_replace('\s+$', '') -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.mydata | default('') }}
    db_admin_password: |-
      {% set ns=namespace() %}
      {%- for myline in (mysql_creds['content'] | b64decode).splitlines() -%}
        {%- if 'password' in myline -%}
          {%- set ns.mydata=myline | regex_replace('^user\s*=\s*','') | regex_replace('\s+$', '') -%}
        {%- endif -%}
      {%- endfor -%}
      {{ ns.mydata | default('') }}
