---
- name: Load OS specific variables
  include_vars: ../vars/rhel.yml

- name: Update server
  yum:
    name: '*'
    state: latest

- name: Add EPEL repository
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
  dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Install Guacamole library requirements
  dnf:
    name:
    - cairo-devel
    - libjpeg-turbo-devel
    - libjpeg-devel
    - libpng-devel
    - uuid-devel
    - freerdp-devel
    - pango-devel
    - libssh2-devel
    - openssl-devel
    - tomcat
    - tomcat-admin-webapps
    - tomcat-webapps
    - haveged   # fixes /dev/random issue
    # to compile the intial code
    - autoconf
    - automake
    - gcc
    - make
    # for SQL Auth
    - mariadb-server
    - mariadb
    - python3-PyMySQL
    state: present

- name: "Start Services"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
  - "mariadb"
  - "haveged"
  - "tomcat"
